/*import type { paths, components } from "./schema.api"; // generated by openapi-typescript

// Schema Obj
type MyType = components["schemas"]["Location.jsonld-infoCompany"];

// Path params
type EndpointParams = paths["/api/events/now"]["get"];

// Response obj
type SuccessResponse =
  paths["/api/events/now"]["get"]["responses"][200]["content"]["application/ld+json"];
type ErrorResponse =
  paths["/api/events/now"]["get"]["responses"][500]["content"]["application/ld+json"]["schema"];


type SuccessResponse =
  paths["/api/events/now"]["get"]["responses"][200]["content"]["application/ld+json"];
*/
