/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/api/companies/{id}": {
    /**
     * Retrieves a Company resource.
     * @description Retrieves a Company resource.
     */
    get: operations["api_companies_id_get"];
  };
  "/api/event_types/{id}": {
    /**
     * Retrieves a EventType resource.
     * @description Retrieves a EventType resource.
     */
    get: operations["api_event_types_id_get"];
  };
  "/api/events/now": {
    /**
     * Retrieves the collection of Event resources.
     * @description Retrieves the collection of Event resources.
     */
    get: operations["api_eventsnow_get_collection"];
  };
  "/api/events/past": {
    /**
     * Retrieves the collection of Event resources.
     * @description Retrieves the collection of Event resources.
     */
    get: operations["api_eventspast_get_collection"];
  };
  "/api/events/{id}": {
    /**
     * Retrieves a Event resource.
     * @description Retrieves a Event resource.
     */
    get: operations["api_events_id_get"];
  };
  "/api/offers": {
    /**
     * Retrieves the collection of Offer resources.
     * @description Retrieves the collection of Offer resources.
     */
    get: operations["api_offers_get_collection"];
  };
  "/api/office": {
    /**
     * Retrieves the collection of Mandate resources.
     * @description Retrieves the collection of Mandate resources.
     */
    get: operations["api_office_get_collection"];
  };
  "/api/partner/challenger": {
    /**
     * Retrieves the collection of Partner resources.
     * @description Retrieves the collection of Partner resources.
     */
    get: operations["api_partnerchallenger_get_collection"];
  };
  "/api/partner/discount": {
    /**
     * Retrieves the collection of Partner resources.
     * @description Retrieves the collection of Partner resources.
     */
    get: operations["api_partnerdiscount_get_collection"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "BeginEndDateEmbeddable.jsonld": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      /** Format: date-time */
      beginDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
    };
    "BeginEndDateEmbeddable.jsonld-challengerCompany": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      /** Format: date-time */
      beginDate?: string | null;
    };
    "BeginEndDateEmbeddable.jsonld-discountCompany": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      /** Format: date-time */
      beginDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
    };
    "BeginEndDateEmbeddable.jsonld-listOffer": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      /** Format: date-time */
      beginDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
    };
    "BeginEndDateTimeEmbeddable.jsonld-detailEvent": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      /** Format: date-time */
      beginDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
    };
    "Company.jsonld-challengerCompany": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      name?: string;
      img?: string | null;
      description?: string;
      located?: components["schemas"]["Location.jsonld-challengerCompany"][];
      activities?: components["schemas"]["CompanyType.jsonld-challengerCompany"][];
    };
    "Company.jsonld-discountCompany": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      name?: string;
      img?: string | null;
      banner?: string | null;
      description?: string;
      located?: components["schemas"]["Location.jsonld-discountCompany"][];
      activities?: components["schemas"]["CompanyType.jsonld-discountCompany"][];
    };
    "Company.jsonld-infoCompany": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      name?: string;
      img?: string | null;
      description?: string;
      located?: components["schemas"]["Location.jsonld-infoCompany"][];
      activities?: components["schemas"]["CompanyType.jsonld-infoCompany"][];
    };
    "Company.jsonld-listOffer": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      name?: string;
      img?: string | null;
    };
    "CompanyType.jsonld-challengerCompany": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      label?: string;
    };
    "CompanyType.jsonld-discountCompany": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      label?: string;
    };
    "CompanyType.jsonld-infoCompany": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      label?: string;
    };
    "Event.jsonld-detailEvent": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      name?: string;
      img?: string | null;
      description?: string;
      onlyMiagist?: boolean;
      nadhPrice?: string | null;
      adhPrice?: string | null;
      quotaStu?: number | null;
      types?: components["schemas"]["EventType.jsonld-detailEvent"][];
      situated?: components["schemas"]["Location.jsonld-detailEvent"][];
      bgedDate?: components["schemas"]["BeginEndDateTimeEmbeddable.jsonld-detailEvent"];
      /** Format: date-time */
      publicationDate?: string | null;
    };
    "Event.jsonld-minimalEvent": {
      "@id"?: string;
      "@type"?: string;
      id?: number;
      name?: string;
      img?: string | null;
    };
    "EventType.jsonld-detailEvent": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      label?: string;
    };
    "EventType.jsonld-detailEventType": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      label?: string;
      description?: string;
    };
    "Hub.jsonld": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id: number;
      name: string;
      description: string;
      roles?: components["schemas"]["Role.jsonld"][];
    };
    "Location.jsonld-challengerCompany": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      label?: string;
      latitude?: number | null;
      longitude?: number | null;
      country?: string | null;
      city?: string | null;
      postalCode?: string | null;
      adresse?: string | null;
    };
    "Location.jsonld-detailEvent": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      label?: string;
      latitude?: number | null;
      longitude?: number | null;
      country?: string | null;
      city?: string | null;
      postalCode?: string | null;
      adresse?: string | null;
    };
    "Location.jsonld-discountCompany": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      label?: string;
      latitude?: number | null;
      longitude?: number | null;
      country?: string | null;
      city?: string | null;
      postalCode?: string | null;
      adresse?: string | null;
    };
    "Location.jsonld-infoCompany": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id?: number;
      label?: string;
      latitude?: number | null;
      longitude?: number | null;
      country?: string | null;
      city?: string | null;
      postalCode?: string | null;
      adresse?: string | null;
    };
    "Mandate.jsonld": {
      "@id"?: string;
      "@type"?: string;
      id?: number;
      roles?: components["schemas"]["Role.jsonld"][];
      student: components["schemas"]["Student.jsonld"];
      visible?: boolean;
      bgedDate?: components["schemas"]["BeginEndDateEmbeddable.jsonld"];
      /** Format: date-time */
      creationDate?: string;
      /** Format: date-time */
      lastEditDate?: string | null;
      edited?: boolean;
    };
    "Offer.jsonld-listOffer": {
      "@id"?: string;
      "@type"?: string;
      id: number;
      label: string;
      description: string;
      /** Format: date-time */
      endProvidDate: string;
      keyWords?: string[];
      provide: components["schemas"]["Company.jsonld-listOffer"];
      bgedDate?: components["schemas"]["BeginEndDateEmbeddable.jsonld-listOffer"];
    };
    "Partner.jsonld-challengerCompany": {
      "@id"?: string;
      "@type"?: string;
      id?: number;
      company?: components["schemas"]["Company.jsonld-challengerCompany"];
      bgedDate?: components["schemas"]["BeginEndDateEmbeddable.jsonld-challengerCompany"];
    };
    "Partner.jsonld-discountCompany": {
      "@id"?: string;
      "@type"?: string;
      id?: number;
      company?: components["schemas"]["Company.jsonld-discountCompany"];
      advantages?: string | null;
      bgedDate?: components["schemas"]["BeginEndDateEmbeddable.jsonld-discountCompany"];
    };
    "Role.jsonld": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id: number;
      hub: components["schemas"]["Hub.jsonld"];
      name: string;
      priority?: number;
    };
    "Student.jsonld": {
      "@context"?: OneOf<[string, {
        "@vocab": string;
        /** @enum {string} */
        hydra: "http://www.w3.org/ns/hydra/core#";
        [key: string]: unknown;
      }]>;
      "@id"?: string;
      "@type"?: string;
      id: number;
      name: string;
      lastName: string;
      img?: string | null;
      studentNumber: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      level: "l3" | "m1" | "m2" | "wk" | "oth";
      /** Format: date-time */
      creationDate?: string;
      /** Format: date-time */
      lastEditDate?: string | null;
      edited?: boolean;
    };
  };
  responses: {
  };
  parameters: {
  };
  requestBodies: {
  };
  headers: {
  };
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Retrieves a Company resource.
   * @description Retrieves a Company resource.
   */
  api_companies_id_get: {
    parameters: {
      path: {
        /** @description Company identifier */
        id: string;
      };
    };
    responses: {
      /** @description Company resource */
      200: {
        content: {
          "application/ld+json": components["schemas"]["Company.jsonld-infoCompany"];
        };
      };
      /** @description Resource not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Retrieves a EventType resource.
   * @description Retrieves a EventType resource.
   */
  api_event_types_id_get: {
    parameters: {
      path: {
        /** @description EventType identifier */
        id: string;
      };
    };
    responses: {
      /** @description EventType resource */
      200: {
        content: {
          "application/ld+json": components["schemas"]["EventType.jsonld-detailEventType"];
        };
      };
      /** @description Resource not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Retrieves the collection of Event resources.
   * @description Retrieves the collection of Event resources.
   */
  api_eventsnow_get_collection: {
    parameters: {
      query?: {
        /** @description The collection page number */
        page?: number;
      };
    };
    responses: {
      /** @description Event collection */
      200: {
        content: {
          "application/ld+json": {
            "hydra:member": components["schemas"]["Event.jsonld-minimalEvent"][];
            "hydra:totalItems"?: number;
            /**
             * @example {
             *   "@id": "string",
             *   "type": "string",
             *   "hydra:first": "string",
             *   "hydra:last": "string",
             *   "hydra:previous": "string",
             *   "hydra:next": "string"
             * }
             */
            "hydra:view"?: {
              /** Format: iri-reference */
              "@id"?: string;
              "@type"?: string;
              /** Format: iri-reference */
              "hydra:first"?: string;
              /** Format: iri-reference */
              "hydra:last"?: string;
              /** Format: iri-reference */
              "hydra:previous"?: string;
              /** Format: iri-reference */
              "hydra:next"?: string;
            };
            "hydra:search"?: {
              "@type"?: string;
              "hydra:template"?: string;
              "hydra:variableRepresentation"?: string;
              "hydra:mapping"?: ({
                  "@type"?: string;
                  variable?: string;
                  property?: string | null;
                  required?: boolean;
                })[];
            };
          };
        };
      };
    };
  };
  /**
   * Retrieves the collection of Event resources.
   * @description Retrieves the collection of Event resources.
   */
  api_eventspast_get_collection: {
    parameters: {
      query?: {
        /** @description The collection page number */
        page?: number;
      };
    };
    responses: {
      /** @description Event collection */
      200: {
        content: {
          "application/ld+json": {
            "hydra:member": components["schemas"]["Event.jsonld-minimalEvent"][];
            "hydra:totalItems"?: number;
            /**
             * @example {
             *   "@id": "string",
             *   "type": "string",
             *   "hydra:first": "string",
             *   "hydra:last": "string",
             *   "hydra:previous": "string",
             *   "hydra:next": "string"
             * }
             */
            "hydra:view"?: {
              /** Format: iri-reference */
              "@id"?: string;
              "@type"?: string;
              /** Format: iri-reference */
              "hydra:first"?: string;
              /** Format: iri-reference */
              "hydra:last"?: string;
              /** Format: iri-reference */
              "hydra:previous"?: string;
              /** Format: iri-reference */
              "hydra:next"?: string;
            };
            "hydra:search"?: {
              "@type"?: string;
              "hydra:template"?: string;
              "hydra:variableRepresentation"?: string;
              "hydra:mapping"?: ({
                  "@type"?: string;
                  variable?: string;
                  property?: string | null;
                  required?: boolean;
                })[];
            };
          };
        };
      };
    };
  };
  /**
   * Retrieves a Event resource.
   * @description Retrieves a Event resource.
   */
  api_events_id_get: {
    parameters: {
      path: {
        /** @description Event identifier */
        id: string;
      };
    };
    responses: {
      /** @description Event resource */
      200: {
        content: {
          "application/ld+json": components["schemas"]["Event.jsonld-detailEvent"];
        };
      };
      /** @description Resource not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Retrieves the collection of Offer resources.
   * @description Retrieves the collection of Offer resources.
   */
  api_offers_get_collection: {
    parameters: {
      query?: {
        /** @description The collection page number */
        page?: number;
      };
    };
    responses: {
      /** @description Offer collection */
      200: {
        content: {
          "application/ld+json": {
            "hydra:member": components["schemas"]["Offer.jsonld-listOffer"][];
            "hydra:totalItems"?: number;
            /**
             * @example {
             *   "@id": "string",
             *   "type": "string",
             *   "hydra:first": "string",
             *   "hydra:last": "string",
             *   "hydra:previous": "string",
             *   "hydra:next": "string"
             * }
             */
            "hydra:view"?: {
              /** Format: iri-reference */
              "@id"?: string;
              "@type"?: string;
              /** Format: iri-reference */
              "hydra:first"?: string;
              /** Format: iri-reference */
              "hydra:last"?: string;
              /** Format: iri-reference */
              "hydra:previous"?: string;
              /** Format: iri-reference */
              "hydra:next"?: string;
            };
            "hydra:search"?: {
              "@type"?: string;
              "hydra:template"?: string;
              "hydra:variableRepresentation"?: string;
              "hydra:mapping"?: ({
                  "@type"?: string;
                  variable?: string;
                  property?: string | null;
                  required?: boolean;
                })[];
            };
          };
        };
      };
    };
  };
  /**
   * Retrieves the collection of Mandate resources.
   * @description Retrieves the collection of Mandate resources.
   */
  api_office_get_collection: {
    parameters: {
      query?: {
        /** @description The collection page number */
        page?: number;
      };
    };
    responses: {
      /** @description Mandate collection */
      200: {
        content: {
          "application/ld+json": {
            "hydra:member": components["schemas"]["Mandate.jsonld"][];
            "hydra:totalItems"?: number;
            /**
             * @example {
             *   "@id": "string",
             *   "type": "string",
             *   "hydra:first": "string",
             *   "hydra:last": "string",
             *   "hydra:previous": "string",
             *   "hydra:next": "string"
             * }
             */
            "hydra:view"?: {
              /** Format: iri-reference */
              "@id"?: string;
              "@type"?: string;
              /** Format: iri-reference */
              "hydra:first"?: string;
              /** Format: iri-reference */
              "hydra:last"?: string;
              /** Format: iri-reference */
              "hydra:previous"?: string;
              /** Format: iri-reference */
              "hydra:next"?: string;
            };
            "hydra:search"?: {
              "@type"?: string;
              "hydra:template"?: string;
              "hydra:variableRepresentation"?: string;
              "hydra:mapping"?: ({
                  "@type"?: string;
                  variable?: string;
                  property?: string | null;
                  required?: boolean;
                })[];
            };
          };
        };
      };
    };
  };
  /**
   * Retrieves the collection of Partner resources.
   * @description Retrieves the collection of Partner resources.
   */
  api_partnerchallenger_get_collection: {
    parameters: {
      query?: {
        /** @description The collection page number */
        page?: number;
      };
    };
    responses: {
      /** @description Partner collection */
      200: {
        content: {
          "application/ld+json": {
            "hydra:member": components["schemas"]["Partner.jsonld-challengerCompany"][];
            "hydra:totalItems"?: number;
            /**
             * @example {
             *   "@id": "string",
             *   "type": "string",
             *   "hydra:first": "string",
             *   "hydra:last": "string",
             *   "hydra:previous": "string",
             *   "hydra:next": "string"
             * }
             */
            "hydra:view"?: {
              /** Format: iri-reference */
              "@id"?: string;
              "@type"?: string;
              /** Format: iri-reference */
              "hydra:first"?: string;
              /** Format: iri-reference */
              "hydra:last"?: string;
              /** Format: iri-reference */
              "hydra:previous"?: string;
              /** Format: iri-reference */
              "hydra:next"?: string;
            };
            "hydra:search"?: {
              "@type"?: string;
              "hydra:template"?: string;
              "hydra:variableRepresentation"?: string;
              "hydra:mapping"?: ({
                  "@type"?: string;
                  variable?: string;
                  property?: string | null;
                  required?: boolean;
                })[];
            };
          };
        };
      };
    };
  };
  /**
   * Retrieves the collection of Partner resources.
   * @description Retrieves the collection of Partner resources.
   */
  api_partnerdiscount_get_collection: {
    parameters: {
      query?: {
        /** @description The collection page number */
        page?: number;
      };
    };
    responses: {
      /** @description Partner collection */
      200: {
        content: {
          "application/ld+json": {
            "hydra:member": components["schemas"]["Partner.jsonld-discountCompany"][];
            "hydra:totalItems"?: number;
            /**
             * @example {
             *   "@id": "string",
             *   "type": "string",
             *   "hydra:first": "string",
             *   "hydra:last": "string",
             *   "hydra:previous": "string",
             *   "hydra:next": "string"
             * }
             */
            "hydra:view"?: {
              /** Format: iri-reference */
              "@id"?: string;
              "@type"?: string;
              /** Format: iri-reference */
              "hydra:first"?: string;
              /** Format: iri-reference */
              "hydra:last"?: string;
              /** Format: iri-reference */
              "hydra:previous"?: string;
              /** Format: iri-reference */
              "hydra:next"?: string;
            };
            "hydra:search"?: {
              "@type"?: string;
              "hydra:template"?: string;
              "hydra:variableRepresentation"?: string;
              "hydra:mapping"?: ({
                  "@type"?: string;
                  variable?: string;
                  property?: string | null;
                  required?: boolean;
                })[];
            };
          };
        };
      };
    };
  };
}
