<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDIa1nRg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDIa1nRg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDIa1nRg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDIa1nRg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDIa1nRg\App_KernelDevDebugContainer([
    'container.build_hash' => 'DIa1nRg',
    'container.build_id' => 'd1e5d9d0',
    'container.build_time' => 1709571974,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDIa1nRg');
